[package]
name = "PostMint"
version = "0.0.0"

[dependencies]
AptosFramework = { local = "../../framework/aptos-framework" }
AptosToken = { local = "../../framework/aptos-token" }

[addresses]
aptos_framework = "0x1"
# the post_mint_reveal_nft here are for unit test purposes.
# in production, we should change it to "post_mint_reveal_nft = "_""
post_mint_reveal_nft = "0xcafe"